<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>4afec9b4-f252-4d76-aca9-0068c72ad436</testSuiteGuid>
   <testCaseLink>
      <guid>1cca2610-1e3c-4c84-9174-1fd959d535f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login test</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c184f465-77a3-4beb-99f9-22047fbbe034</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>c184f465-77a3-4beb-99f9-22047fbbe034</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>7cb82554-3bb9-46b6-9fe3-b449302f95e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c184f465-77a3-4beb-99f9-22047fbbe034</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>13cfd7c5-6f85-4cd6-8afd-cc54e06814e8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
